version: "3.7"

volumes:
  nextcloud:

networks:
  nextcloud:
    driver: bridge

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud

  app:
    image: nextcloud:fpm-alpine
    volumes:
      - nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./php.ini:/usr/local/etc/php/php.ini:ro
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=db
    networks:
      - nextcloud

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - nextcloud

  redis:
    hostname: redis
    image: redis:5-alpine
    restart: always
    networks:
      - nextcloud